@startuml
'https://plantuml.com/sequence-diagram
title Compartmentalized Backend and Frontend
skinparam ParticipantPadding 200

actor User as u
participant Browser as b
participant Host as h

group 1. Enter Url
u->b:enter url
b->h:HTTP request
b<--h:HTML with link jsbundle
b->h:request jsbundle
b<--h:jsbundle
b->h:request download assets and style
b<--h:asset and style
b->b:JS DOM manipulation to do render Full page
activate b
end

group 2. Interaction
u->b:user interaction
b->h:XML HTTP request
b<--h:HTML/JSON
b->b:DOM manipulation
activate b
end

deactivate b

group 3. Interaction
u->b:user interaction
b->h:XML HTTP request
b<--h:HTML/JSON
b->b:DOM manipulation
activate b
end

deactivate b
deactivate b
@enduml